# Generated by Django 5.2.6 on 2025-09-15 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField()),
                ('mac', models.CharField(blank=True, max_length=17)),
                ('hostname', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('online', models.BooleanField(default=True)),
                ('ports', models.JSONField(blank=True, default=list)),
                ('os', models.CharField(blank=True, max_length=50)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_data', to='agents.agent')),
            ],
        ),
    ]
